[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
solvent_labs = "4JD6CXFyXdn2z5trTvcMm42yMygUmkdnbvJmPSd98KbQ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/home/top/.config/solana/id.json"

[scripts]
client = "yarn run ts-node client/*.ts"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
